version: '3'

services:
  app:
    image: node:15
    container_name: app
    volumes:
      - ../node-challenge:/usr/src/app
    ports:
      - 3000:3000
    restart: always
    tty: true

  database:
    platform: linux/x86_64
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: database
    restart: always
    tty: true
    environment:
      - MYSQL_DATABASE=node_challenge
      - MYSQL_ROOT_PASSWORD=root

