version: '3'

services:
  app:
    build: 
      context: src
    container_name: app
    entrypoint: dockerize -wait tcp://database:3306 -timeout 20s node index.js
    volumes:
      - ./src:/usr/src/app
    ports:
      - 3000:3000
    restart: always
    tty: true
    depends_on:
      - database

  database:
    platform: linux/x86_64
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: database
    restart: always
    tty: true
    environment:
      - MYSQL_DATABASE=node_challenge
      - MYSQL_ROOT_PASSWORD=root

  nginx:
    build: 
      context: ./nginx
    image: cidstein/nginx
    container_name: nginx
    ports: 
      - "8080:80"
    depends_on:
      - app
